### ISSUE TITLE
fix: ny-house-price-estimator is outdated and broken

### ISSUE THREAD

**Issue by aacecandev** [konstellation-io/ny-house-price-estimator#36]
As a KAI Server ML Engineer
I want the ny-house-price-estimator application fixed
In order to be able to deploy it to both the new isolated INT and PRO environments

As a KAI Product Leader/Owner
I want the ny-house-price-estimator application fixed
In order to guarantee that, when we have the opportunity of a demo with a client, the application is correctly working in an updated environment

** Tasks **

- [X] Deploy the frontend and backend in INT and kai-server
- [X] Run a new training to make fix dependencies and release a new model version compatible with Python 3.9
- [x] Discuss where should this model be saved
- [x] Create a new krt and test it against both environments

** Definition of Done **

- [x] Deployed and tested in INT
- [x] Deployed and tested in kai-server
